services:
  - type: web
    name: ammar-absolute-solution
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ammar-absolute-db
          property: connectionString

databases:
  - name: ammar-absolute-db
    plan: free
